//
// Terminaux  Copyright (C) 2023-2026  Aptivi
//
// This file is part of Terminaux
//
// Terminaux is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Terminaux is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

using System.Collections.Generic;

namespace Terminaux.Writer.CyclicWriters.Renderer.Tools
{
    internal static class CowNameMapping
    {
        internal static Dictionary<CowName, string> cowNameStrings = new()
        {
            { CowName.C3PO, "C3PO" },
            { CowName.R2_D2, "R2-D2" },
            { CowName.USA, "USA" },
            { CowName.Ackbar, "ackbar" },
            { CowName.Aperture_blank, "aperture-blank" },
            { CowName.Aperture, "aperture" },
            { CowName.Armadillo, "armadillo" },
            { CowName.Atat, "atat" },
            { CowName.Atom, "atom" },
            { CowName.Awesome_face, "awesome-face" },
            { CowName.Banana, "banana" },
            { CowName.Bearface, "bearface" },
            { CowName.Beavis_zen, "beavis.zen" },
            { CowName.Bees, "bees" },
            { CowName.Bill_the_cat, "bill-the-cat" },
            { CowName.Biohazard, "biohazard" },
            { CowName.Bishop, "bishop" },
            { CowName.Black_mesa, "black-mesa" },
            { CowName.Bong, "bong" },
            { CowName.Box, "box" },
            { CowName.Broken_heart, "broken-heart" },
            { CowName.Bud_frogs, "bud-frogs" },
            { CowName.Bunny, "bunny" },
            { CowName.Cake_with_candles, "cake-with-candles" },
            { CowName.Cake, "cake" },
            { CowName.Cat, "cat" },
            { CowName.Cat2, "cat2" },
            { CowName.Catfence, "catfence" },
            { CowName.Charizardvice, "charizardvice" },
            { CowName.Charlie, "charlie" },
            { CowName.Cheese, "cheese" },
            { CowName.Chessmen, "chessmen" },
            { CowName.Chito, "chito" },
            { CowName.Claw_arm, "claw-arm" },
            { CowName.Clippy, "clippy" },
            { CowName.Companion_cube, "companion-cube" },
            { CowName.Cower, "cower" },
            { CowName.Cowfee, "cowfee" },
            { CowName.Cthulhu_mini, "cthulhu-mini" },
            { CowName.Cube, "cube" },
            { CowName.Daemon, "daemon" },
            { CowName.Dalek_shooting, "dalek-shooting" },
            { CowName.Dalek, "dalek" },
            { CowName.Default, "default" },
            { CowName.Docker_whale, "docker-whale" },
            { CowName.Doge, "doge" },
            { CowName.Dolphin, "dolphin" },
            { CowName.Dragon_and_cow, "dragon-and-cow" },
            { CowName.Dragon, "dragon" },
            { CowName.Ebi_furai, "ebi_furai" },
            { CowName.Elephant_in_snake, "elephant-in-snake" },
            { CowName.Elephant, "elephant" },
            { CowName.Elephant2, "elephant2" },
            { CowName.Explosion, "explosion" },
            { CowName.Eyes, "eyes" },
            { CowName.Fat_banana, "fat-banana" },
            { CowName.Fat_cow, "fat-cow" },
            { CowName.Fence, "fence" },
            { CowName.Fire, "fire" },
            { CowName.Flaming_sheep, "flaming-sheep" },
            { CowName.Fox, "fox" },
            { CowName.Ghost, "ghost" },
            { CowName.Ghostbusters, "ghostbusters" },
            { CowName.Glados, "glados" },
            { CowName.Goat, "goat" },
            { CowName.Goat2, "goat2" },
            { CowName.Golden_eagle, "golden-eagle" },
            { CowName.Hand, "hand" },
            { CowName.Happy_whale, "happy-whale" },
            { CowName.Hedgehog, "hedgehog" },
            { CowName.Hellokitty, "hellokitty" },
            { CowName.Hippie, "hippie" },
            { CowName.Hiya, "hiya" },
            { CowName.Hiyoko, "hiyoko" },
            { CowName.Homer, "homer" },
            { CowName.Hypno, "hypno" },
            { CowName.Ibm, "ibm" },
            { CowName.Iwashi, "iwashi" },
            { CowName.Jellyfish, "jellyfish" },
            { CowName.Karl_marx, "karl_marx" },
            { CowName.Kilroy, "kilroy" },
            { CowName.King, "king" },
            { CowName.Kiss, "kiss" },
            { CowName.Kitten, "kitten" },
            { CowName.Kitty, "kitty" },
            { CowName.Knight, "knight" },
            { CowName.Koala, "koala" },
            { CowName.Kosh, "kosh" },
            { CowName.Lamb, "lamb" },
            { CowName.Lamb2, "lamb2" },
            { CowName.Lightbulb, "lightbulb" },
            { CowName.Lobster, "lobster" },
            { CowName.Lollerskates, "lollerskates" },
            { CowName.Luke_koala, "luke-koala" },
            { CowName.Mailchimp, "mailchimp" },
            { CowName.Maze_runner, "maze-runner" },
            { CowName.Mech_and_cow, "mech-and-cow" },
            { CowName.Meow, "meow" },
            { CowName.Milk, "milk" },
            { CowName.Minotaur, "minotaur" },
            { CowName.Mona_lisa, "mona-lisa" },
            { CowName.Moofasa, "moofasa" },
            { CowName.Mooghidjirah, "mooghidjirah" },
            { CowName.Moojira, "moojira" },
            { CowName.Moose, "moose" },
            { CowName.Mule, "mule" },
            { CowName.Mutilated, "mutilated" },
            { CowName.Nyan, "nyan" },
            { CowName.Octopus, "octopus" },
            { CowName.Okazu, "okazu" },
            { CowName.Owl, "owl" },
            { CowName.Pawn, "pawn" },
            { CowName.Periodic_table, "periodic-table" },
            { CowName.Personality_sphere, "personality-sphere" },
            { CowName.Pinball_machine, "pinball-machine" },
            { CowName.Psychiatrichelp, "psychiatrichelp" },
            { CowName.Psychiatrichelp2, "psychiatrichelp2" },
            { CowName.Pterodactyl, "pterodactyl" },
            { CowName.Queen, "queen" },
            { CowName.Radio, "radio" },
            { CowName.Ren, "ren" },
            { CowName.Renge, "renge" },
            { CowName.Robot, "robot" },
            { CowName.Robotfindskitten, "robotfindskitten" },
            { CowName.Roflcopter, "roflcopter" },
            { CowName.Rook, "rook" },
            { CowName.Sachiko, "sachiko" },
            { CowName.Satanic, "satanic" },
            { CowName.Seahorse_big, "seahorse-big" },
            { CowName.Seahorse, "seahorse" },
            { CowName.Sheep, "sheep" },
            { CowName.Shikato, "shikato" },
            { CowName.Shrug, "shrug" },
            { CowName.Skeleton, "skeleton" },
            { CowName.Small, "small" },
            { CowName.Smiling_octopus, "smiling-octopus" },
            { CowName.Snoopy, "snoopy" },
            { CowName.Snoopyhouse, "snoopyhouse" },
            { CowName.Snoopysleep, "snoopysleep" },
            { CowName.Spidercow, "spidercow" },
            { CowName.Squid, "squid" },
            { CowName.Squirrel, "squirrel" },
            { CowName.Stegosaurus, "stegosaurus" },
            { CowName.Stimpy, "stimpy" },
            { CowName.Sudowoodo, "sudowoodo" },
            { CowName.Supermilker, "supermilker" },
            { CowName.Surgery, "surgery" },
            { CowName.Tableflip, "tableflip" },
            { CowName.Taxi, "taxi" },
            { CowName.Telebears, "telebears" },
            { CowName.Template, "template" },
            { CowName.Threader, "threader" },
            { CowName.Threecubes, "threecubes" },
            { CowName.Toaster, "toaster" },
            { CowName.Tortoise, "tortoise" },
            { CowName.Turkey, "turkey" },
            { CowName.Turtle, "turtle" },
            { CowName.Tux_big, "tux-big" },
            { CowName.Tux, "tux" },
            { CowName.Tweety_bird, "tweety-bird" },
            { CowName.Vader_koala, "vader-koala" },
            { CowName.Vader, "vader" },
            { CowName.Weeping_angel, "weeping-angel" },
            { CowName.Whale, "whale" },
            { CowName.Wizard, "wizard" },
            { CowName.Wood, "wood" },
            { CowName.World, "world" },
            { CowName.Www, "www" },
            { CowName.Yasuna_01, "yasuna_01" },
            { CowName.Yasuna_02, "yasuna_02" },
            { CowName.Yasuna_03, "yasuna_03" },
            { CowName.Yasuna_03a, "yasuna_03a" },
            { CowName.Yasuna_04, "yasuna_04" },
            { CowName.Yasuna_05, "yasuna_05" },
            { CowName.Yasuna_06, "yasuna_06" },
            { CowName.Yasuna_07, "yasuna_07" },
            { CowName.Yasuna_08, "yasuna_08" },
            { CowName.Yasuna_09, "yasuna_09" },
            { CowName.Yasuna_10, "yasuna_10" },
            { CowName.Yasuna_11, "yasuna_11" },
            { CowName.Yasuna_12, "yasuna_12" },
            { CowName.Yasuna_13, "yasuna_13" },
            { CowName.Yasuna_14, "yasuna_14" },
            { CowName.Yasuna_16, "yasuna_16" },
            { CowName.Yasuna_17, "yasuna_17" },
            { CowName.Yasuna_18, "yasuna_18" },
            { CowName.Yasuna_19, "yasuna_19" },
            { CowName.Yasuna_20, "yasuna_20" },
            { CowName.Ymd_udon, "ymd_udon" },
            { CowName.Zen_noh_milk, "zen-noh-milk" },
        };

        internal static string GetCowNameFrom(CowName name) =>
            cowNameStrings[name];
    }
}
