//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminaux.ColorDataGen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminaux.ColorDataGen.Resources.ConsoleResources", typeof(ConsoleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;colorId&quot;: 0,
        ///        &quot;hexString&quot;: &quot;#000000&quot;,
        ///        &quot;rgb&quot;: {
        ///            &quot;r&quot;: 0,
        ///            &quot;g&quot;: 0,
        ///            &quot;b&quot;: 0
        ///        },
        ///        &quot;hsl&quot;: {
        ///            &quot;h&quot;: 0,
        ///            &quot;s&quot;: 0,
        ///            &quot;l&quot;: 0
        ///        },
        ///        &quot;name&quot;: &quot;Black&quot;
        ///    },
        ///    {
        ///        &quot;colorId&quot;: 1,
        ///        &quot;hexString&quot;: &quot;#800000&quot;,
        ///        &quot;rgb&quot;: {
        ///            &quot;r&quot;: 128,
        ///            &quot;g&quot;: 0,
        ///            &quot;b&quot;: 0
        ///        },
        ///        &quot;hsl&quot;: {
        ///            &quot;h&quot;: 0,
        ///            &quot;s&quot;: 100,
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleColorsData {
            get {
                return ResourceManager.GetString("ConsoleColorsData", resourceCulture);
            }
        }
    }
}
