//
// Terminaux  Copyright (C) 2023-2024  Aptivi
//
// This file is part of Terminaux
//
// Terminaux is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Terminaux is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

using Microsoft.CodeAnalysis;
using Newtonsoft.Json;
using System.IO;
using System.Linq;
using System.Text;
using Terminaux.Colors.Data;

namespace Terminaux.ColorDataGen
{
    [Generator]
    public class ColorPropGen : ISourceGenerator
    {
        private string colorContent = "";

        public void Execute(GeneratorExecutionContext context)
        {
            // Get the color data content
            var asm = typeof(ColorPropGen).Assembly;
            var stream = asm.GetManifestResourceStream($"{asm.GetName().Name}.Resources.ConsoleColorsData.json");
            using var reader = new StreamReader(stream);
            colorContent = reader.ReadToEnd();

            // Now, populate the color enumerations and data properties
            PopulateColorEnums(context);
            PopulateColorData(context);
        }

        public void Initialize(GeneratorInitializationContext context)
        { }

        private void PopulateColorData(GeneratorExecutionContext context)
        {
            string header =
                $$"""
                //
                // Terminaux  Copyright (C) 2023-2024  Aptivi
                //
                // This file is part of Terminaux
                //
                // Terminaux is free software: you can redistribute it and/or modify
                // it under the terms of the GNU General Public License as published by
                // the Free Software Foundation, either version 3 of the License, or
                // (at your option) any later version.
                //
                // Terminaux is distributed in the hope that it will be useful,
                // but WITHOUT ANY WARRANTY, without even the implied warranty of
                // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
                // GNU General Public License for more details.
                //
                // You should have received a copy of the GNU General Public License
                // along with this program.  If not, see <https://www.gnu.org/licenses/>.
                //
                
                // <auto-generated/>

                namespace Terminaux.Colors.Data
                {
                    public partial class ConsoleColorData
                    {

                """;
            string footer =
                $$"""
                    }
                }
                """;
            var builder = new StringBuilder(header);

            // Read all the console color data
            var list = JsonConvert.DeserializeObject<ConsoleColorData[]>(colorContent);
            var names = list.Select((data) => data.Name).ToArray();
            if (list is null)
                return;

            // First, populate all the color data properties
            foreach (var colorData in list)
            {
                string colorHex = colorData.HexString;
                var colorRgb = colorData.RGB;
                string colorName = colorData.Name;
                int colorId = colorData.ColorId;
                string propName = names[colorId];
                builder.AppendLine(
                    $$"""
                            /// <summary>
                            /// [{{colorHex}}] Gets the console colors data for the {{propName}} color
                            /// </summary>
                            public static ConsoleColorData {{propName}} =>
                                new("{{colorHex}}", {{colorRgb.r}}, {{colorRgb.g}}, {{colorRgb.b}}, "{{colorName}}", {{colorId}});
                    """
                );
            }
            builder.AppendLine();

            // Then, populate a partial function that gets all this data
            builder.AppendLine(
                """
                        public static partial ConsoleColorData[] GetColorData()
                        {
                            return
                            [
                """
            );
            foreach (var colorData in list)
            {
                int colorId = colorData.ColorId;
                string propName = names[colorId];
                builder.AppendLine(
                    $$"""
                                    {{propName}},
                    """
                );
            }
            builder.AppendLine(
                """
                            ];
                        }
                """
            );

            // Add the source code to the compilation
            builder.AppendLine(footer);
            context.AddSource("ConsoleColorData.g.cs", builder.ToString());
        }

        private void PopulateColorEnums(GeneratorExecutionContext context)
        {
            string header =
                $$"""
                //
                // Terminaux  Copyright (C) 2023-2024  Aptivi
                //
                // This file is part of Terminaux
                //
                // Terminaux is free software: you can redistribute it and/or modify
                // it under the terms of the GNU General Public License as published by
                // the Free Software Foundation, either version 3 of the License, or
                // (at your option) any later version.
                //
                // Terminaux is distributed in the hope that it will be useful,
                // but WITHOUT ANY WARRANTY, without even the implied warranty of
                // MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
                // GNU General Public License for more details.
                //
                // You should have received a copy of the GNU General Public License
                // along with this program.  If not, see <https://www.gnu.org/licenses/>.
                //
                
                // <auto-generated/>

                namespace Terminaux.Colors.Data
                {
                    /// <summary>
                    /// All 255 console colors
                    /// </summary>
                    public enum ConsoleColors
                    {
                
                """;
            string footer =
                $$"""
                    }
                }
                """;
            var builder = new StringBuilder(header);

            // Read all the console color data
            var list = JsonConvert.DeserializeObject<ConsoleColorData[]>(colorContent);
            if (list is null)
                return;

            // First, populate all the color data properties
            foreach (var colorData in list)
            {
                string colorHex = colorData.HexString;
                string colorName = colorData.Name;
                var colorRgb = colorData.RGB;
                builder.AppendLine(
                    $$"""
                            /// <summary>
                            /// [{{colorHex}}] Represents the {{colorName}} color with the RGB value of {{colorRgb.r}};{{colorRgb.g}};{{colorRgb.b}}
                            /// </summary>
                            {{colorName}},
                    """
                );
            }

            // Add the source code to the compilation
            builder.AppendLine(footer);
            context.AddSource("ConsoleColors.cs", builder.ToString());
        }
    }
}
