//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terminaux.SequenceTypesGen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SequenceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SequenceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terminaux.SequenceTypesGen.Resources.SequenceResources", typeof(SequenceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;type&quot;: &quot;Csi&quot;,
        ///    &quot;sequences&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;CsiInsertBlankCharacters&quot;,
        ///        &quot;regex&quot;: &quot;(\\x9B|\\x1B\\[)[0-9]*[@]&quot;,
        ///        &quot;format&quot;: &quot;{VtSequenceBasicChars.EscapeChar}[{{0}}@&quot;,
        ///        &quot;arguments&quot;: [
        ///          {
        ///            &quot;name&quot;: &quot;blanks&quot;,
        ///            &quot;type&quot;: &quot;System.Int32&quot;
        ///          }
        ///        ]
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;CsiShiftLeftColumns&quot;,
        ///        &quot;regex&quot;: &quot;(\\x9B|\\x1B\\[)[0-9]*[ ][@]&quot;,
        ///        &quot;format&quot;: &quot;{VtSequenceBasicChars.EscapeChar}[{{0}} @&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sequences {
            get {
                return ResourceManager.GetString("Sequences", resourceCulture);
            }
        }
    }
}
