name: API Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: "Make API Reference"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Fetching the source
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'
      - name: Setup DocFX
        run: dotnet tool install --global docfx
      - name: Generating Documentation
        run: |
          make rel-ci
          make doc
      - name: Saving changes to gh-pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'docs'
      - id: deployment
        uses: actions/deploy-pages@v5
