name: KS API Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Make API Reference"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Fetching the source
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Solution Compilation
        run: dotnet build --configuration Release
      - uses: "nunit/docfx-action@master"
        name: Generating documentation
        with:
          args: DocGen/docfx.json
      - name: Saving changes to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          commit_message: "Updated documentation to reflect latest changes"
          personal_token: ${{ secrets.DOCGEN_TOKEN }}
          publish_dir: ./docs/
          publish_branch: gh-pages
